### ISSUE TITLE
Can not add google account

### ISSUE THREAD

**Issue by edek51** [owncloud/mail#1148]
I can not add any google accounts. I believe that i have tried everything. Log is showing:

"fsockopen(): unable to connect to imap.alt3.gmail-smtp-in.l.google.com:143 (Operation timed out) at /usr/home/ansambl/domains/own.ansambl.eu/public_html/apps/mail/lib/service/autoconfig.php#420"
"fsockopen(): unable to connect to alt3.gmail-smtp-in.l.google.com:993 (Operation timed out) at /usr/home/ansambl/domains/own.ansambl.eu/public_html/apps/mail/lib/service/autoconfig.php#420" 	
"fsockopen(): unable to connect to alt3.gmail-smtp-in.l.google.com:585 (Operation timed out) at /usr/home/ansambl/domains/own.ansambl.eu/public_html/apps/mail/lib/service
/autoconfig.php#420" 

Is there something i can do about that? 

Version
ownCloud 8.2.0 (beta) 
Mail 0.2.1

### Steps to reproduce
1.add google acount
2.wait
3.error massage sayin that can not connect with serwer

### Expected behaviour
add google account

### Actual behaviour
imposible to add google account

### Server configuration
**Operating system**:

**Web server:**
Apache
**Database:**
Mysql
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**

```
Activity 2.1.3
Deleted files 0.7.0
File Locking 
First Run Wizard 1.1
Gallery 14.2.0
Mail Template Editor 0.1
Notifications 0.1.0
PDF Viewer 0.7
Provisioning API 0.3.0
Share Files 0.7.0
Text Editor 2.0
Updater 0.6
Versions 1.1.0
Video Viewer 0.1.3
Calendar 0.8.0
Contacts 0.5.0.0
Mail 
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'passwordsalt' => 'KpXzR7U+C9BlRXeADrD6DkWvIdLuId',
  'secret' => 'FAiJw4g3ZoRkSKwBqtzTfKa6aV0SVrTmLunH+352lVo2OtIH',
  'trusted_domains' => 
  array (
    0 => 'www.own.ansambl.eu',
  ),
  'datadirectory' => '/usr/home/ansambl/domains/own.ansambl.eu/public_html/data',
  'overwrite.cli.url' => 'http://www.own.ansambl.eu',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'm1247_own',
  'dbhost' => 'mysql4.mydevil.net',
  'dbtableprefix' => 'oc_',
  'instanceid' => 'oce2b8fskpi8',
  'dbuser' => 'm1247_own',
  'dbpassword' => 'xxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'mail4.mydevil.net',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'j.bulas@ansambl.eu',
  'mail_smtppassword' => 'xxxx',
  'mail_from_address' => 'j.bulas',
  'mail_domain' => 'ansambl.eu',
  'mail_smtpauthtype' => 'PLAIN',
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox, Chrome
**Operating system:**
Windows 10, Debian
#### ownCloud log (data/owncloud.log)
http://pastebin.com/52u5tUGE

**Comment by jancborchardt** [comment]
@ChristophWurst didn’t you have a Google account connected? Or @DeepDiver1975? Can you reproduce this?

**Comment by 19kestier** [comment]
Server: ownCloud 8.2 on Ubuntu 14.04
Google IMAP Info: https://support.google.com/mail/troubleshooter/1668960?authuser=1&hl=en&rd=1#ts=1665018%2C1665144

I also have 2-factor enabled on my account. I am using an app password (https://support.google.com/accounts/answer/185833) to login.

I am not able to access my Gmail through this app, either. I get this error when trying to add my Google Account: "Creating account failed: Error connecting to SMTP server." I get this error if I enter IMAP and SMTP details in, or if I leave them blank.

I'd love to get any information needed to fix the issue!

**Comment by jancborchardt** [comment]
I assume you already followed the Gmail troubleshooting instructions at https://github.com/owncloud/mail/blob/master/README.md#gmail ?

What more info do you need @ChristophWurst @Gomez @zinks-?

**Comment by danielcb** [comment]
Is there a solution for this besides the troubleshooting guide? I still have this exact issue with oc 8.2 and the current nightly builds.

**Comment by danielcb** [comment]
ssl on 993 works, starttls on 413 does not, at least with my setup.

**Comment by zinks-** [comment]
Are those two parameters from config.php safe to post on github ?
```
  'passwordsalt' => '***',
  'secret' => '****',
```

**Comment by 19kestier** [comment]
@danielcb Didn't work for me. Still this:
![screenshot 2016-02-10 at 7 38 45 pm](https://cloud.githubusercontent.com/assets/4749568/12966624/040fc172-d02e-11e5-817e-c22d1348fd54.png)

**Comment by danielcb** [comment]
@19kestier sorry for the late reply. What worked for me is:
imap: 993 ssl/tls
smtp: 587, starttls

**Comment by 19kestier** [comment]
@danielcb For some reason I'm still getting the same result. What in the world could be going on here?

**Comment by jancborchardt** [comment]
@Gomez I assume you meant 0.5? Since we’re done with 0.4 :)

**Comment by Gomez** [comment]
Yes. Try to move it :P Does not work for me :( Github Bug?

**Comment by jancborchardt** [comment]
Was able to change it thanks to @mikemcquaid. Apparently the original issue was too long (due to the owncloud.log) and the check for that caused a bug. Put the log in a pastebin as workaround. :)

**Comment by ChristophWurst** [comment]
There was a bug with autoconfig, which has been fixed with #1405. Feel free to re-open if there's still something not working.

**Comment by 19kestier** [comment]
Even after updating the extension, I am still not able to add my account.
