### ISSUE TITLE
'Error while deleting message.' error

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/mail#408]
### Steps to reproduce
1. Delete an inbox email

### Expected behaviour
The app should delete the selected email.

### Actual behaviour
I get an 'Error while deleting message.' error.

### Server configuration
**Operating system**:
Arch Linux
**Web server:**
php built-in
**Database:**
MariaDB 10.0.15-1
**PHP version:**
PHP 5.6.3 (cli) (built: Nov 13 2014 18:31:57)
**ownCloud version:**
ownCloud 7.0.3 (stable)
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
- standard apps (files, contacts, calendar,...)
- mail app

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Firefox 34.0.5

**Operating system:**
Arch Linux

#### Web server error log
```
[Sat Dec  6 11:39:27 2014] ::1:44119 [500]: /index.php/apps/mail/accounts/6/folders/SU5CT1g%3D/messages/16
```

#### ownCloud log (data/owncloud.log)
```
{"app":"index","message":"Horde_Imap_Client_Exception: Could not open mailbox \"1\". [200]","level":4,"time":"2014-12-06T10:39:27+00:00"}
```

I took a look at the code but couldn't really debug it. What I have found out:
- ``acount`` - ``deleteMessage`` is called
- ``$hordeSourceMailBox`` is set to ``INBOX`` which seem right to me
- ``$hordeTrashMailBox`` is set to ``Trash`` which is the name of my trash folder
- the exception is thrown in ``Horde_Imap_Client_Socket``s ``copy`` method

**Comment by jancborchardt** [comment]
@DeepDiver1975 @zinks- @PoPoutdoor are you able to reproduce and/or fix this issue? :)

**Comment by PoPoutdoor** [comment]
@jancborchardt I haven't upgraded OC from 7.0.2 yet, I can test this by upgrading to 7.0.3 first (with latest mail app code).

**Comment by wurstchristoph** [comment]
This issue seems to be caused by the following lines:
https://github.com/horde/horde/blob/master/framework/Imap_Client/lib/Horde/Imap/Client/Socket.php#L2115-L2120
For some reason, ```$this->_selected``` is NULL there, so an exception is thrown inside ```copy``` because the mailbox can not be found

When I comment out those lines, messages can be deleted. However, I have no idea on how to resolve this...

**Comment by jancborchardt** [comment]
@DeepDiver1975 @zinks- @LukasReschke any idea here ^?

**Comment by jancborchardt** [comment]
@wurstchristoph does this problem still exist? Or can you now delete emails?

**Comment by wurstchristoph** [comment]
Yes, the problem still exists. Whenever I delete a message I get "Error while deleting message."

The message is moved to trash anyway...

**Comment by Xenopathic** [comment]
Unable to reproduce. Running oC Mail master on oC 8.0.2, vendor packages match those in composer.lock. Mail gets moved to trash without any problems (aside from a string-to-array conversion problem in logging fixed in #550). @jancborchardt @DeepDiver1975 Can you reproduce?

**Comment by jancborchardt** [comment]
I could never reproduce.

**Comment by wurstchristoph** [comment]
Well, I'm still having the issue. The strange part is, horde does not log any error:

```------------------------------
>> Wed, 29 Apr 2015 06:29:40 +0000
>> Connection to: imap://imap.world4you.com/
>> Server connection took 0.0088 seconds.
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
C: 1 AUTHENTICATE PLAIN [INITIAL CLIENT RESPONSE (username: xxx@yyy.at)]
S: 1 OK [CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA CHILDREN ID] Logged in
>> Command 1 took 0.0533 seconds.
C: 2 LIST "" *
S: * LIST (\HasNoChildren) "." "test folder"
S: * LIST (\HasNoChildren) "." "testfolder2"
S: * LIST (\HasNoChildren) "." "Sent"
S: * LIST (\HasNoChildren) "." "Drafts"
S: * LIST (\HasNoChildren) "." "Trash"
S: * LIST (\HasNoChildren) "." "INBOX"
S: 2 OK List completed.
>> Command 2 took 0.0096 seconds.
C: 3 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 143)
S: 3 OK Status completed.
>> Command 3 took 0.0114 seconds.
C: 4 STATUS INBOX (MESSAGES)
S: * STATUS "INBOX" (MESSAGES 143)
S: 4 OK Status completed.
>> Command 4 took 0.009 seconds.
C: 5 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 100)
S: 5 OK Status completed.
>> Command 5 took 0.0104 seconds.
C: 6 STATUS Sent (MESSAGES)
S: * STATUS "Sent" (MESSAGES 100)
S: 6 OK Status completed.
>> Command 6 took 0.0087 seconds.
C: 7 STATUS Drafts (MESSAGES)
S: * STATUS "Drafts" (MESSAGES 12)
S: 7 OK Status completed.
>> Command 7 took 0.0084 seconds.
C: 8 STATUS Drafts (MESSAGES)
S: * STATUS "Drafts" (MESSAGES 12)
S: 8 OK Status completed.
>> Command 8 took 0.0083 seconds.
C: 9 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 32)
S: 9 OK Status completed.
>> Command 9 took 0.009 seconds.
C: 10 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 32)
S: 10 OK Status completed.
>> Command 10 took 0.011 seconds.
C: 11 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 143 RECENT 0 UIDNEXT 168 UIDVALIDITY 1428599115 UNSEEN 0)
S: 11 OK Status completed.
>> Command 11 took 0.0092 seconds.
C: 12 STATUS INBOX (MESSAGES RECENT UIDNEXT UIDVALIDITY UNSEEN)
S: * STATUS "INBOX" (MESSAGES 143 RECENT 0 UIDNEXT 168 UIDVALIDITY 1428599115 UNSEEN 0)
S: 12 OK Status completed.
>> Command 12 took 0.0084 seconds.
C: 13 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 32)
S: 13 OK Status completed.
>> Command 13 took 0.0119 seconds.
C: 14 STATUS Trash (MESSAGES)
S: * STATUS "Trash" (MESSAGES 32)
S: 14 OK Status completed.
>> Command 14 took 0.0085 seconds.
C: 15 SELECT INBOX
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
S: * 143 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1428599115] UIDs valid
S: * OK [UIDNEXT 168] Predicted next UID
S: * OK [HIGHESTMODSEQ 1] Highest
S: 15 OK [READ-WRITE] Select completed.
>> Command 15 took 0.0114 seconds.
C: 16 UID COPY 160 Trash
S: 16 OK [COPYUID 1428599118 160 33] Copy completed.
>> Command 16 took 0.0162 seconds.
C: 17 UID SEARCH DELETED NOT UID 160
S: * SEARCH
S: 17 OK Search completed (0.000 secs).
>> Command 17 took 0.0083 seconds.
C: 18 UID STORE 160 +FLAGS \deleted
S: * 138 FETCH (UID 160 FLAGS (\Deleted \Seen))
S: 18 OK Store completed.
>> Command 18 took 0.0095 seconds.
C: 19 CLOSE
S: 19 OK Close completed.
>> Command 19 took 0.0096 seconds.
C: 20 SELECT ""
S: 20 NO Empty mailbox name.
>> Command 20 took 0.0078 seconds.
C: 21 LOGOUT
S: * BYE Logging out
S: 21 OK Logout completed.
>> Command 21 took 0.0084 seconds.
```

The logs look good. However, the exception is still thrown. As the message is deleted as expected, maybe the lines
```
C: 20 SELECT ""
S: 20 NO Empty mailbox name.
>> Command 20 took 0.0078 seconds
```
are the problem, but that's only a guess.

@Xenopathic I could provide you with a test account on my shared hosters mail server (world4you.com). Then you should be able to reproduce this hopefully :)

Tested with current master with all composer dependencies up to date.

**Comment by Xenopathic** [comment]
Ah, got it. By overriding my Dovecot's IMAP CAPABILITY response (`imap_capability = CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE`) to match what your server responds with, I get the same error (and the faulty `SELECT ""` command). When using the default capabilities, everything works fine (`CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE`).

I'm investigating...

**Comment by Xenopathic** [comment]
Right, the capability that causes this is `UIDPLUS`. Without it, I get the error, with it (default) I do not. Time to dig into the Horde libraries!

**Comment by Xenopathic** [comment]
Well, the problem is obvious now that I look at the code. https://github.com/horde/horde/blob/master/framework/Imap_Client/lib/Horde/Imap/Client/Socket.php#L2112 is run to perform the expunge on mails with the deleted flag, however that function sets `$this->_selected` to null (the connection is closed, obviously). However, the code then expects `$this->_selected` to still be valid for https://github.com/horde/horde/blob/master/framework/Imap_Client/lib/Horde/Imap/Client/Socket.php#L2119 !

**Comment by Xenopathic** [comment]
I fixed the issue in Horde and submitted a patch: https://bugs.horde.org/ticket/13970. Nothing to do but wait now :smile:

**Comment by wurstchristoph** [comment]
Great! Thanks a lot for debugging this :+1:

**Comment by Xenopathic** [comment]
@wurstchristoph Want to test the patch to see if it fixes your problem? Get the patch from the attached ticket, then `cd` to `vendor/pear-pear.horde.org/Horde_Imap_Client`, then run `patch -p 4 < /path/to/patch.patch`. It might help get the patch reviewed by Horde quicker too :smile:

**Comment by wurstchristoph** [comment]
Applied the patch and now I can finally delete my mails :grinning:

**Comment by jancborchardt** [comment]
@wurstchristoph best also comment on @Xenopathic’s ticket https://bugs.horde.org/ticket/13970 :)

@Xenopathic you have karoshi.org.uk? That’s hilarious :'D

**Comment by Xenopathic** [comment]
Merged! https://github.com/horde/horde/commit/afe1cd81f7e5fe374d5f7952956cdf15319601da

**Comment by Xenopathic** [comment]
@jancborchardt What's hilarious about my email? :p

**Comment by jancborchardt** [comment]
Well, the meaning of Karoshi. ;)

**Comment by jancborchardt** [comment]
@Xenopathic so will this be backported in Horde or something like that?

**Comment by Xenopathic** [comment]
@jancborchardt RE email: hehe yeah the translation of that is very... interesting. Still, I've had it for years, I'm surprised you only noticed it now!

It will be coming out in Horde Imap Client 2.28.1, hopefully soon.

**Comment by wurstchristoph** [comment]
@jancborchardt @Xenopathic It's fixed now :smile:

**Comment by jancborchardt** [comment]
@wurstchristoph so what was it? :D

**Comment by wurstchristoph** [comment]
@jancborchardt it was a bug in horde, seems to be fixed with the latest version :-)
